name: Clang

on: [ "push" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci_clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang: [
          { version: "5.0" },
          { version: "6.0" },
          { version: "7" },
          { version: "8" },
          { version: "9" },
          { version: "10" },
          { version: "11" },
          { version: "12" },
          { version: "13" },
          { version: "14" },
          { version: "15" },
          { version: "16" },
          { version: "17" },
        ]
    container: croemheld/icarus-ci:clang-${{ matrix.clang.version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set environment variables
        run: echo "CC=clang CXX=clang++" >> "$GITHUB_ENV"
      - name: Run CMake and build ICARUS
        run: |
          mkdir -p build && cd build && cmake -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ .. \
          && ninja icarus
