name: Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci_clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [
          { clang: "5.0" },
          { clang: "6.0" },
          { clang: "7" },
          { clang: "8" },
          { clang: "9" },
          { clang: "10" },
          { clang: "11" },
          { clang: "12" },
          { clang: "13" },
          { clang: "14" },
          { clang: "15" },
        ]
    container: croemheld/icarus-ci:clang-${{ matrix.compiler.clang }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set environment variables
        run: echo "CC=clang CXX=clang++" >> "$GITHUB_ENV"
      - name: Run CMake and build ICARUS
        run: |
          mkdir -p build && cd build && cmake -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ .. \
          && ninja icarus
