name: Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci_clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [
          { clang: "5.0" },
          { clang: "6.0" },
          { clang: "7" },
          { clang: "8" },
          { clang: "9" },
          { clang: "10" },
          { clang: "11" },
          { clang: "12" },
          { clang: "13" },
          { clang: "14" },
          { clang: "15" },
          { clang: "16" },
          { clang: "17" },
        ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Get minimum CMake version for build
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.13.0
      - name: Set environment variables
        run: echo "CC=clang CXX=clang++" >> "$GITHUB_ENV"
      - name: Install base packages and LLVM
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git python3 cmake flex bison
          mkdir llvm && cd llvm
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh ${{ matrix.compiler.clang }} all
      - name: Run CMake and build ICARUS
        run: |
          mkdir -p build && cd build && cmake -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ .. \
          && ninja icarus
