name: Coverage

on:
  workflow_run:
    workflows: ["Clang"]
    types:
      - completed

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: croemheld/icarus-ci:clang-15
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Download ICARUS build artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: build
          path: build
          github-token: ${{ secrets.ARTIFACT_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Fix and run unit tests for ICARUS
        run: |
          chmod 755 ./build/tests/TestIcarus && ./build/tests/TestIcarus
      - name: Generate gcovr coverage output
        run: |
          ./tools/run-gcovr-coverage.sh --xml build
      - name: Upload gcovr report to codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: croemheld/icarus
          file: ./build/coverage/coverage.xml

