name: Docker

on:
  workflow_run:
    workflows: ["Clang"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-dispatcher:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        version: [ "5.0", "6.0", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17"]
    uses: ./.github/workflows/docker-common.yml
    with:
      version: ${{ matrix.version }}
