name: Docker Common

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      docker-username:
        description: 'Dockerhub username'
        required: true
      docker-password:
        description: 'DockerHub password'
        required: true

jobs:
  docker-change:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.count }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check the changed files
        id: changed-files
        uses: croemheld/git-diff-action@v1
        with:
          base: origin/main
          comp: ${{ github.ref_name }}
          glob: '+(cmake|docker)/*'
          type: 'M'

  docker-icarus:
    runs-on: ubuntu-latest
    needs: docker-change
    if: ${{ needs.docker-change.outputs.changed-files }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}
      - name: Build container image
        run: ./docker/build.sh --jobs 2 --llvm-version ${{ inputs.version }}
      - name: Push container image to Docker Hub
        if: ${{ github.ref_name == 'main' }}
        run: docker push croemheld/icarus-ci:clang-${{ inputs.version }}
