name: Docker

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-change:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.count }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check the changed files
        id: changed-files
        uses: croemheld/git-diff-action@v1
        with:
          base: origin/main
          comp: ${{ github.ref_name }}
          glob: '**/{cmake,docker}/*'
          type: 'M'
  docker-icarus:
    runs-on: ubuntu-latest
    needs: docker-change
    if: ${{ needs.docker-change.outputs.changed-files != 0 }}
    strategy:
      fail-fast: false
      matrix:
        version: [ "5.0", "6.0", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Free up GitHub runner space
        run: |
          df -h
          sudo rm -rf "/usr/share/dotnet"
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Build container image
        run: ./docker/build.sh --jobs 2 --llvm-version ${{ matrix.version }}
      - name: Save compressed container image
        if: ${{ github.ref_name != 'main' }}
        run: |
          docker save croemheld/icarus-ci:clang-${{ matrix.version }} | gzip > clang-${{ matrix.version }}.tar.gz
      - name: Upload container image as artifact
        if: ${{ github.ref_name != 'main' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: clang-${{ matrix.version }}
          path: clang-${{ matrix.version }}.tar.gz
          retention-days: 1
      - name: Push container image to Docker Hub
        if: ${{ github.ref_name == 'main' }}
        run: docker push croemheld/icarus-ci:clang-${{ matrix.version }}
