name: Docker

on: ["push"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-change:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.count }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check the changed files
        id: changed-files
        uses: croemheld/git-diff-action@v1
        with:
          base: origin/main
          comp: ${{ github.ref_name }}
          glob: '+(cmake|docker)/*'
          type: 'M'
  docker-icarus:
    runs-on: ubuntu-latest
    needs: docker-change
    if: ${{ needs.docker-change.outputs.changed-files }}
    strategy:
      fail-fast: false
      matrix:
        version: [ "5.0", "6.0", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build container image
        run: ./docker/build.sh --jobs 2 --llvm-version ${{ matrix.version }}
      - name: Push container image to Docker Hub
        if: ${{ github.ref_name == 'main' }}
        run: docker push croemheld/icarus-ci:clang-${{ matrix.version }}
