name: Docker

on: [ "push" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci_change:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'main' }}
    outputs:
      changed-llvm-libraries: ${{ steps.changed-llvm-libraries.outputs.count }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check LLVM libraries file
        id: changed-llvm-libraries
        uses: croemheld/git-diff-action@v1
        with:
          base: origin/main
          comp: ${{ github.ref_name }}
          glob: 'cmake/LLVMLibraries.cmake'
          type: 'M'

  ci_docker:
    runs-on: ubuntu-latest
    needs: ci_change
    if: ${{ needs.ci_change.outputs.changed-llvm-libraries }}
    strategy:
      fail-fast: false
      matrix:
        clang: [
          { version: "5.0" },
          { version: "6.0" },
          { version: "7" },
          { version: "8" },
          { version: "9" },
          { version: "10" },
          { version: "11" },
          { version: "12" },
          { version: "13" },
          { version: "14" },
          { version: "15" },
          { version: "16" },
          { version: "17" },
        ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build container image
        run: ./docker/build.sh --jobs 2 --llvm-version ${{ matrix.clang.version }}
      - name: Push container image to Docker Hub
        if: ${{ github.ref_name == 'main' }}
        run: docker push croemheld/icarus-ci:clang-${{ matrix.clang.version }}
