name: Doxygen

on:
  push:
    branches: [ "main" ]

jobs:
  doxygen-build:
    runs-on: ubuntu-latest
    container: croemheld/icarus-ci:clang-17
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install base packages and Doxygen
        run: |
          apt-get update
          apt-get install --no-install-recommends -y build-essential git python3 flex bison graphviz doxygen
      - name: Create doxygen documentation
        run: |
          mkdir build && cd build
          cmake -DOPTION_BUILD_DOCS=On ..
          make doxygen
      - name: Create .nojekyll file
        run: touch build/docs/doxygen/html/.nojekyll
      - name: Fix permissions
        run: |
          chmod -c -R +rX build/docs/doxygen/html | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: build/docs/doxygen/html

  doxygen-deploy:
    needs: doxygen-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy doxygen artifacts to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
