name: Doxygen

on:
  push:
    branches: [ "main" ]

jobs:
  doxygen-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install base packages
        run: sudo apt-get update && sudo apt-get install -y build-essential git python3 cmake flex bison graphviz
      - name: Clone and build latest doxygen repository
        run: |
          git clone https://github.com/doxygen/doxygen.git && mkdir -p doxygen/build
          cd doxygen/build && cmake -G "Unix Makefiles" .. && make && sudo make install
      - name: Create doxygen documentation
        run: |
          mkdir build && cd build
          cmake -DOPTION_BUILD_DOCS=On ..
          make doxygen
      - name: Create .nojekyll file
        run: touch build/docs/doxygen/html/.nojekyll
      - name: Archive doxygen artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build/docs/doxygen/html

  doxygen-deploy:
    needs: doxygen-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download doxygen artifacts
        uses: actions/download-artifact@v3
        with:
          name: github-pages
      - name: Deploy doxygen artifacts to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
